// generated by @greymass/abi2core

import { Asset, Float32, Name, Struct, TimePointSec, UInt32, UInt64 } from "@greymass/eosio"

@Struct.type("AccountUnstake")
export class AccountUnstake extends Struct {
    @Struct.field(UInt64) quantity!:UInt64
    @Struct.field(TimePointSec) available_after!:TimePointSec
}

@Struct.type("Accounts")
export class Accounts extends Struct {
    @Struct.field(Name) account!:Name
    @Struct.field(UInt64) staked!:UInt64
    @Struct.field(UInt64) fah_points!:UInt64
    @Struct.field(UInt64) claimable!:UInt64
    @Struct.field(AccountUnstake, { array: true }) unstake!:AccountUnstake[]
    @Struct.field(TimePointSec) last_points_update!:TimePointSec
}

@Struct.type("Config")
export class Config extends Struct {
    @Struct.field(Asset) min_stake!:Asset
    @Struct.field(Float32) fah_points_payout_ratio!:Float32
    @Struct.field(UInt32) stake_unlock_delay_sec!:UInt32
    @Struct.field(Name) oracle_account!:Name
    @Struct.field(Float32) stake_bonus_divisor!:Float32
    @Struct.field(Name) manager_account!:Name
    @Struct.field(Name) token_account!:Name
    @Struct.field(Float32) manager_cut_pct!:Float32
}

@Struct.type("Global")
export class Global extends Struct {
    @Struct.field(UInt64) total_minted!:UInt64
    @Struct.field(UInt64) manager_claimable!:UInt64
}

@Struct.type("addfahpoints")
export class Addfahpoints extends Struct {
    @Struct.field(Name) account!:Name
    @Struct.field(UInt32) add_fah_points!:UInt32
}

@Struct.type("claim")
export class Claim extends Struct {
    @Struct.field(Name) account!:Name
}

@Struct.type("claimunstake")
export class Claimunstake extends Struct {
    @Struct.field(Name) account!:Name
}

@Struct.type("clearconfig")
export class Clearconfig extends Struct {
}

@Struct.type("initunstake")
export class Initunstake extends Struct {
    @Struct.field(Name) account!:Name
    @Struct.field(Asset) quantity!:Asset
}

@Struct.type("logaddpoints")
export class Logaddpoints extends Struct {
    @Struct.field(Name) account!:Name
    @Struct.field(UInt32) added_fah_points!:UInt32
    @Struct.field(Asset) base_payout!:Asset
    @Struct.field(Asset) stake_bonus!:Asset
}

@Struct.type("managerclaim")
export class Managerclaim extends Struct {
}

@Struct.type("setconfig")
export class Setconfig extends Struct {
    @Struct.field(Config) config!:Config
}
